[functions]
  directory = "netlify/functions"

[[headers]]
for = "/video/*"
[headers.values]
Cache-Control = "public, max-age=2147483647, immutable"

[[headers]]
for = "/js/clarity.js"
[headers.values]
Cache-Control = "public, max-age=2147483647, immutable"
